export const BikesData = [
  {
    id: 1,
    name: "Mitsubishi",
    avgRating: 1,
    model: "GTO",
    color: "Teal",
    location: "Longos",
    isAvailable: true,
  },
  {
    id: 2,
    name: "Lexus",
    avgRating: 4,
    model: "IS",
    color: "Green",
    location: "Yuncao",
    isAvailable: true,
  },
  {
    id: 3,
    name: "Pontiac",
    avgRating: 1,
    model: "Firefly",
    color: "Blue",
    location: "West Palm Beach",
    isAvailable: false,
  },
  {
    id: 4,
    name: "MINI",
    avgRating: 2,
    model: "Cooper",
    color: "Pink",
    location: "Novovarshavka",
    isAvailable: false,
  },
  {
    id: 5,
    name: "Suzuki",
    avgRating: 5,
    model: "Sidekick",
    color: "Maroon",
    location: "Shouyan",
    isAvailable: true,
  },
  {
    id: 6,
    name: "Subaru",
    avgRating: 3,
    model: "Impreza",
    color: "Purple",
    location: "Las Garcitas",
    isAvailable: false,
  },
  {
    id: 7,
    name: "Subaru",
    avgRating: 4,
    model: "SVX",
    color: "Violet",
    location: "Złoczew",
    isAvailable: true,
  },
  {
    id: 8,
    name: "Hyundai",
    avgRating: 5,
    model: "Sonata",
    color: "Goldenrod",
    location: "Birštonas",
    isAvailable: false,
  },
  {
    id: 9,
    name: "Volkswagen",
    avgRating: 3,
    model: "Touareg 2",
    color: "Violet",
    location: "Pjanići",
    isAvailable: true,
  },
  {
    id: 10,
    name: "BMW",
    avgRating: 2,
    model: "X5",
    color: "Teal",
    location: "Kalembutillu",
    isAvailable: true,
  },
  {
    id: 11,
    name: "Lotus",
    avgRating: 2,
    model: "Exige",
    color: "Crimson",
    location: "Habingkloang",
    isAvailable: true,
  },
  {
    id: 12,
    name: "Saab",
    avgRating: 5,
    model: "900",
    color: "Purple",
    location: "Chengqiao",
    isAvailable: false,
  },
  {
    id: 13,
    name: "Volkswagen",
    avgRating: 3,
    model: "Cabriolet",
    color: "Crimson",
    location: "Beixin",
    isAvailable: true,
  },
  {
    id: 14,
    name: "Toyota",
    avgRating: 5,
    model: "Celica",
    color: "Crimson",
    location: "Mingcheng",
    isAvailable: true,
  },
  {
    id: 15,
    name: "Dodge",
    avgRating: 3,
    model: "Durango",
    color: "Aquamarine",
    location: "Almalaguês",
    isAvailable: false,
  },
];

export const ReservationsData = [
  {
    id: 1,
    bikeID: "98",
    bikeName: "Volkswagen",
    fromDate: "2021/03/18",
    toDate: "2021/09/11",
  },
  {
    id: 2,
    bikeID: "6104",
    bikeName: "Volkswagen",
    fromDate: "2021/09/16",
    toDate: "2022/01/01",
  },
  {
    id: 3,
    bikeID: "45",
    bikeName: "Infiniti",
    fromDate: "2021/12/28",
    toDate: "2021/03/21",
  },
  {
    id: 4,
    bikeID: "4684",
    bikeName: "Lexus",
    fromDate: "2021/08/21",
    toDate: "2021/03/04",
  },
  {
    id: 5,
    bikeID: "122",
    bikeName: "Suzuki",
    fromDate: "2021/09/22",
    toDate: "2021/04/09",
  },
  {
    id: 6,
    bikeID: "6141",
    bikeName: "Nissan",
    fromDate: "2021/12/15",
    toDate: "2021/08/23",
  },
  {
    id: 7,
    bikeID: "6665",
    bikeName: "Mercedes-Benz",
    fromDate: "2021/08/07",
    toDate: "2021/06/27",
  },
  {
    id: 8,
    bikeID: "7074",
    bikeName: "Saab",
    fromDate: "2021/09/22",
    toDate: "2021/03/19",
  },
  {
    id: 9,
    bikeID: "6269",
    bikeName: "BMW",
    fromDate: "2021/10/27",
    toDate: "2021/10/27",
  },
  {
    id: 10,
    bikeID: "1967",
    bikeName: "Mitsubishi",
    fromDate: "2021/03/21",
    toDate: "2022/02/01",
  },
];

export const UsersData = [
  { id: 1, name: "Perle Oene", email: "poene0@tamu.edu", isManager: true },
  {
    id: 2,
    name: "Peri Gunter",
    email: "pgunter1@bloglines.com",
    isManager: false,
  },
  {
    id: 3,
    name: "Muffin Pirkis",
    email: "mpirkis2@imgur.com",
    isManager: false,
  },
  { id: 4, name: "Marvin Fishe", email: "mfishe3@wix.com", isManager: true },
  {
    id: 5,
    name: "Angelika Welman",
    email: "awelman4@census.gov",
    isManager: true,
  },
  { id: 6, name: "Nertie Gocke", email: "ngocke5@state.gov", isManager: true },
  {
    id: 7,
    name: "Rayner Gregoretti",
    email: "rgregoretti6@storify.com",
    isManager: true,
  },
  {
    id: 8,
    name: "Michaeline Ferrey",
    email: "mferrey7@abc.net.au",
    isManager: false,
  },
  {
    id: 9,
    name: "Adelind Vina",
    email: "avina8@aboutads.info",
    isManager: false,
  },
  {
    id: 10,
    name: "D'arcy Weond",
    email: "dweond9@addtoany.com",
    isManager: false,
  },
];
